### ISSUE TITLE
Logo nav

### ISSUE THREAD

**Issue by Nidev-lab** [pablopaul01/Hotel-Frontend#53]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que al hacer click en el logo del nav se redirija al inicio de la pagina.

## Resultado actual

• Al hacer click no redirige a ningun sitio.

## Captura

![image](https://github.com/pablopaul01/Hotel-Frontend/assets/53904695/f714ba98-e3fc-49c9-b765-aee290ee7de9)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by pablopaul01** [comment]
Buenas noches, se agregó el redireccionamiento observado faltante en el navbar y en el footer.
