### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [pablopaul01/Hotel-Frontend#54]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

•  Que al hacer click en los botones redirijan a dicho lugar.

## Resultado actual

•Los botones no cumplen ninguna accion.

## Captura

![image](https://github.com/pablopaul01/Hotel-Frontend/assets/53904695/21b32542-c69d-465e-a969-1df5c8b37b7d)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by pablopaul01** [comment]
Buenas tardes, agregamos el direccionamiento a la pagina de error ya que las redes solo eran simbolicas
